subdir-$(DATE)+=mod_date.mk
subdir-$(FORMPARSER_DEPECATED)+=mod_formparser.mk
subdir-$(OPENSSL)+=mod_openssl.mk
subdir-$(WOLFSSL)+=mod_wolfssl.mk
subdir-$(WEBSTREAM)+=mod_webstream.mk
subdir-$(METHODLOCK)+=mod_methodlock.mk
subdir-$(TINYSVCMDNS)+=mod_tinysvcmdns.mk
subdir-$(VHOSTS_DEPRECATED)+=mod_vhosts.mk
