subdir-$(WEBSOCKET_RT)+=websocket.mk

subdir-$(DATE)+=mod_date.mk
subdir-$(FORMPARSER_DEPECATED)+=mod_formparser.mk
subdir-$(OPENSSL)+=mod_openssl.mk
subdir-$(WOLFSSL)+=mod_wolfssl.mk
subdir-$(WEBSTREAM)+=mod_webstream.mk
subdir-$(METHODLOCK_DEPRECATED)+=mod_methodlock.mk
subdir-$(TINYSVCMDNS_DEPRECATED)+=mod_tinysvcmdns.mk
subdir-$(VHOST)+=mod_vhost.mk
subdir-$(UPGRADE)+=mod_upgrade.mk
