################################################################################
#
# LIBOUISTITI
#
################################################################################

LIBOUISTITI_VERSION = 3.2.1
LIBOUISTITI_SITE = $(call github,ouistiti-project,libhttpserver,libouistiti-$(LIBOUISTITI_VERSION))
LIBOUISTITI_LICENSE = MIT
LIBOUISTITI_LICENSE_FILES = LICENSE
LIBOUISTITI_INSTALL_STAGING = YES

ifeq ($(BR2_PACKAGE_LIBOUISTITI_MBEDTLS),y)
LIBOUISTITI_DEPENDENCIES += mbedtls
endif
ifeq ($(BR2_PACKAGE_LIBOUISTITI_OPENSSL),y)
LIBOUISTITI_DEPENDENCIES += openssl
endif
ifeq ($(BR2_PACKAGE_LIBOUISTITI_WOLFSSL),y)
LIBOUISTITI_DEPENDENCIES += wolfssl
endif

LIBOUISTITI_CONFIGURE_OPTS+=USE_PTHREAD=$(BR2_TOOLCHAIN_HAS_THREADS)
LIBOUISTITI_CONFIGURE_OPTS+=HTTPCLIENT_FEATURE=$(BR2_PACKAGE_LIBOUISTITI_CLIENT)

LIBOUISTITI_CONFIGURE_OPTS+=MBEDTLS=$(BR2_PACKAGE_LIBOUISTITI_MBEDTLS)
LIBOUISTITI_CONFIGURE_OPTS+=OPENSSL=$(BR2_PACKAGE_LIBOUISTITI_OPENSSL)
LIBOUISTITI_CONFIGURE_OPTS+=WOLFSSL=$(BR2_PACKAGE_LIBOUISTITI_WOLFSSL)
LIBOUISTITI_CONFIGURE_OPTS+=LIBWEBSOCKET=$(BR2_PACKAGE_LIBOUISTITI_WEBSOCKET)

define LIBOUISTITI_CONFIGURE_CMDS
	$(TARGET_CONFIGURE_OPTS) \
		$(MAKE1) -C $(@D) $(OUISTITI_CONFIGURE_OPTS) $(LIBOUISTITI_CONFIGURE_OPTS) defconfig
endef

define LIBOUISTITI_BUILD_CMDS
	$(TARGET_CONFIGURE_OPTS) \
		$(MAKE1) -C $(@D) $(OUISTITI_MAKE_OPTS)
endef

define LIBOUISTITI_INSTALL_STAGING_CMDS
	$(MAKE) -C $(@D) $(OUISTITI_MAKE_OPTS) \
		DESTDIR="$(STAGING_DIR)" install
endef

define LIBOUISTITI_INSTALL_TARGET_CMDS
	$(MAKE) -C $(@D) $(OUISTITI_MAKE_OPTS) \
		DESTDIR="$(TARGET_DIR)" DEVINSTALL=n install
endef

$(eval $(generic-package))
