################################################################################
#
# LIBOUISTITI
#
################################################################################

LIBOUISTITI_VERSION = 3.2.0
LIBOUISTITI_SITE = $(call github,ouistiti-project,libhttpserver,libouistiti-$(LIBOUISTITI_VERSION))
LIBOUISTITI_LICENSE = MIT
LIBOUISTITI_LICENSE_FILES = LICENSE
LIBOUISTITI_INSTALL_STAGING = YES

LIBOUISTITI_KCONFIG_FILE = $(LIBOUISTITI_PKGDIR)/libhttpserver.config
LIBOUISTITI_KCONFIG_FRAGMENT_FILES = $(call qstrip,$(BR2_PACKAGE_OUISTITI_CONFIG_FRAGMENT_FILES))
LIBOUISTITI_KCONFIG_EDITORS = config
LIBOUISTITI_KCONFIG_OPTS = $(OUISTITI_MAKE_OPTS)

ifeq ($(BR2_PACKAGE_LIBOUISTITI_CLIENT),y)
LIBOUISTITI_CLIENT_OPTS=$(call KCONFIG_ENABLE_OPT,HTTPCLIENT_FEATURES,$(@D)/.config)
else
LIBOUISTITI_CLIENT_OPTS=$(call KCONFIG_DISABLE_OPT,HTTPCLIENT_FEATURES,$(@D)/.config)
endif

ifeq ($(BR2_PACKAGE_LIBOUISTITI_MBEDTLS),y)
LIBOUISTITI_DEPENDENCIES += mbedtls
endif
ifeq ($(BR2_PACKAGE_LIBOUISTITI_OPENSSL),y)
LIBOUISTITI_DEPENDENCIES += openssl
endif
ifeq ($(BR2_PACKAGE_LIBOUISTITI_WOLFSSL),y)
LIBOUISTITI_DEPENDENCIES += wolfssl
endif


define LIBOUISTITI_FEATURES_OPTS
	$(if $(findstring y,$(BR2_TOOLCHAIN_HAS_THREADS)),
		$(call KCONFIG_ENABLE_OPT,USE_PTHREAD,$(@D)/.config),
		$(call KCONFIG_DISABLE_OPT,USE_PTHREAD,$(@D)/.config))
	$(if $(findstring y,$(BR2_PACKAGE_LIBOUISTITI_CLIENT)),
		$(call KCONFIG_ENABLE_OPT,HTTPCLIENT_FEATURES,$(@D)/.config),
		$(call KCONFIG_DISABLE_OPT,HTTPCLIENT_FEATURES,$(@D)/.config))
endef

define LIBOUISTITI_LIBRARIES_OPTS
	$(if $(findstring y,$(BR2_SHARED_LIBS)),
		$(call KCONFIG_ENABLE_OPT,SHARED,$(@D)/.config)
		$(call KCONFIG_DISABLE_OPT,STATIC,$(@D)/.config))
	$(if $(findstring y,$(BR2_STATIC_LIBS)),
		$(call KCONFIG_DISABLE_OPT,SHARED,$(@D)/.config)
		$(call KCONFIG_ENABLE_OPT,STATIC,$(@D)/.config))
	$(if $(findstring y,$(BR2_SHARED_STATIC_LIBS)),
		$(call KCONFIG_ENABLE_OPT,SHARED,$(@D)/.config)
		$(call KCONFIG_ENABLE_OPT,STATIC,$(@D)/.config))
endef

define LIBOUISTITI_HASH_OPTS
	$(if $(findstring y,$(BR2_PACKAGE_LIBOUISTITI_MBEDTLS)),
		$(call KCONFIG_ENABLE_OPT,MBEDTLS,$(@D)/.config),
		$(call KCONFIG_DISABLE_OPT,MBEDTLS,$(@D)/.config))

	$(if $(findstring y,$(BR2_PACKAGE_LIBOUISTITI_OPENSSL)),
		$(call KCONFIG_ENABLE_OPT,OPENSSL,$(@D)/.config),
		$(call KCONFIG_DISABLE_OPT,OPENSSL,$(@D)/.config))

	$(if $(findstring y,$(BR2_PACKAGE_LIBOUISTITI_WOLFSSL)),
		$(call KCONFIG_ENABLE_OPT,WOLFSSL,$(@D)/.config),
		$(call KCONFIG_DISABLE_OPT,WOLFSSL,$(@D)/.config))
endef

define LIBOUISTITI_WEBSOCKET_OPTS
	$(if $(findstring y,$(BR2_PACKAGE_LIBOUISTITI_WEBSOCKET)),
		$(call KCONFIG_ENABLE_OPT,LIBWEBSOCKET,$(@D)/.config),
		$(call KCONFIG_DISABLE_OPT,LIBWEBSOCKET,$(@D)/.config))
endef

define LIBOUISTITI_KCONFIG_FIXUP_CMDS
	$(LIBOUISTITI_FEATURES_OPTS)
	$(LIBOUISTITI_LIBRARIES_OPTS)
	$(LIBOUISTITI_CLIENT_OPTS)
	$(LIBOUISTITI_HASH_OPTS)
	$(LIBOUISTITI_WEBSOCKET_OPTS)
endef

define LIBOUISTITI_BUILD_CMDS
	$(TARGET_CONFIGURE_OPTS) \
		$(MAKE1) -C $(@D) $(OUISTITI_MAKE_OPTS)
endef

define LIBOUISTITI_INSTALL_STAGING_CMDS
	$(MAKE) -C $(@D) $(OUISTITI_MAKE_OPTS) \
		DESTDIR="$(STAGING_DIR)" install
endef

define LIBOUISTITI_INSTALL_TARGET_CMDS
	$(MAKE) -C $(@D) $(OUISTITI_MAKE_OPTS) \
		DESTDIR="$(TARGET_DIR)" DEVINSTALL=n install
endef

$(eval $(kconfig-package))
