#!/bin/bash


echo "Content-Type: text/plain; charset=iso-8859-1"
#echo "Content-Length: 700"
echo
sleep 0.1

echo CGI/1.0 test script report:
echo

echo argc is $#. argv is "$*".
echo

echo SERVER_SOFTWARE = $SERVER_SOFTWARE
echo GATEWAY_INTERFACE = $GATEWAY_INTERFACE
echo SERVER_PROTOCOL = $SERVER_PROTOCOL
echo SERVER_NAME = $SERVER_NAME
echo SERVER_ADDR = $SERVER_ADDR
echo SERVER_PORT = $SERVER_PORT
echo REMOTE_HOST = $REMOTE_HOST
echo REMOTE_ADDR = $REMOTE_ADDR
echo REQUEST_METHOD = $REQUEST_METHOD
echo SCHEME = "$REQUEST_SCHEME"
echo URI = "$REQUEST_URI"
echo QUERY_STRING = "$QUERY_STRING"
echo HTTP_ACCEPT = "$HTTP_ACCEPT"
echo PATH_INFO = "$PATH_INFO"
echo PATH_TRANSLATED = "$PATH_TRANSLATED"
echo SCRIPT_NAME = "$SCRIPT_NAME"
echo USER = $REMOTE_USER
echo AUTH_TYPE = $AUTH_TYPE
echo CONTENT_TYPE = $CONTENT_TYPE
echo CONTENT_LENGTH = $CONTENT_LENGTH

echo CONTENT:
read CONTENT
while [ -n "$CONTENT" ]; do
echo $CONTENT
read CONTENT
done
